# Generated by Django 2.0.10 on 2019-02-02 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('imdbrating', models.CharField(blank=True, max_length=10)),
                ('year', models.IntegerField(blank=True)),
                ('nrofgenre', models.IntegerField(blank=True)),
                ('gen_action', models.CharField(blank=True, max_length=100)),
                ('gen_adult', models.CharField(blank=True, max_length=100)),
                ('gen_adventure', models.CharField(blank=True, max_length=100)),
                ('gen_animation', models.CharField(blank=True, max_length=100)),
                ('gen_biography', models.CharField(blank=True, max_length=100)),
                ('gen_comedy', models.CharField(blank=True, max_length=100)),
                ('gen_crime', models.CharField(blank=True, max_length=100)),
                ('gen_documentary', models.CharField(blank=True, max_length=100)),
                ('gen_drama', models.CharField(blank=True, max_length=100)),
                ('gen_family', models.CharField(blank=True, max_length=100)),
                ('gen_fantasy', models.CharField(blank=True, max_length=100)),
                ('gen_filmnoir', models.CharField(blank=True, max_length=100)),
                ('gen_gameshow', models.CharField(blank=True, max_length=100)),
                ('gen_history', models.CharField(blank=True, max_length=100)),
                ('gen_horror', models.CharField(blank=True, max_length=100)),
                ('gen_music', models.CharField(blank=True, max_length=100)),
                ('gen_musical', models.CharField(blank=True, max_length=100)),
                ('gen_mystery', models.CharField(blank=True, max_length=100)),
                ('gen_news', models.CharField(blank=True, max_length=100)),
                ('gen_realitytv', models.CharField(blank=True, max_length=100)),
                ('gen_romance', models.CharField(blank=True, max_length=100)),
                ('gen_scifi', models.CharField(blank=True, max_length=100)),
                ('gen_short', models.CharField(blank=True, max_length=100)),
                ('gen_sport', models.CharField(blank=True, max_length=100)),
                ('gen_talkshow', models.CharField(blank=True, max_length=100)),
                ('gen_thriller', models.CharField(blank=True, max_length=100)),
                ('gen_war', models.CharField(blank=True, max_length=100)),
                ('gen_western', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movielist', models.ForeignKey(on_delete=None, to='movie.MoviesList')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
