# Generated by Django 2.0.10 on 2019-02-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movieslist_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='sublike',
            field=models.IntegerField(default=0),
        ),
    ]
