# Generated by Django 2.0.10 on 2019-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_subscribe_sublike'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
